# Generated by Django 5.1.1 on 2026-01-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
